// @ts-check
import {
  normalizeApiRequest,
  normalizeApiRequests,
  normalizeApiAssertions,
  normalizeApiCaptures
} from '../cases/api-normalize.js';

// REST/API Playwright spec generation: turn plan cases into the text of a
// `test_api_cases.spec.ts` file plus its embedded runtime helpers. Pure string
// building (no I/O). Extracted verbatim from proguide-service.js; isApiPlanCase
// and generateApiTestSpec are imported back there.

export function isApiPlanCase(testCase) {
  return String(testCase?.type || '').toLowerCase() === 'api' ||
    (Array.isArray(testCase?.requests) && testCase.requests.some((item) => item?.request?.method && item?.request?.path)) ||
    Boolean(testCase?.request?.method && testCase?.request?.path);
}

export function generateApiTestSpec(planCases) {
  const cases = planCases.map((testCase) => {
    return {
      id: testCase.id,
      title: testCase.title,
      debug: Boolean(testCase.debug),
      requests: normalizeApiPlanRequests(testCase).map((request, index) => ({
        ...request,
        sequence: index + 1
      }))
    };
  });
  const markers = cases.map((testCase) => `// [${testCase.id}] ${testCase.title}`).join('\n');
  const declarations = cases.map((testCase) => {
    const caseSource = JSON.stringify(testCase, null, 2)
      .split('\n')
      .map((line, index) => index === 0 ? line : `  ${line}`)
      .join('\n');
    return [
      `test(${JSON.stringify(`[${testCase.id}] ${testCase.title}`)}, async ({ request }) => {`,
      `  const testCase = ${caseSource};`,
      '  await runApiCase(request, testCase);',
      '});'
    ].join('\n');
  }).join('\n\n');
  return [
    "import fs from 'node:fs/promises';",
    "import path from 'node:path';",
    "import { test, expect } from './proguide-test-runtime.mjs';",
    '',
    markers,
    declarations,
    '',
    'async function runApiCase(request, testCase) {',
    '  const variables = {};',
    '  for (const apiStep of testCase.requests) {',
    '    await runApiStep(request, apiStep, variables, testCase);',
    '  }',
    '}',
    '',
    'async function runApiStep(request, apiStep, variables, testCase) {',
    '  const startedAt = new Date().toISOString();',
    '  const startedMs = Date.now();',
    '  const resolvedRequest = resolveRequestValue(apiStep.request, variables);',
    '  const evidence = { assertions: [], captures: [] };',
    '  let response = null;',
    '  let responseBody = null;',
    '  let actualResponse = null;',
    '  let failure = null;',
    '  try {',
    '    response = await test.step(`${apiStep.request.method} ${apiStep.request.path}`, async () => {',
    '      return request.fetch(resolvedRequest.path, requestOptions(resolvedRequest));',
    '    });',
    '',
    "    responseBody = await test.step('read response body', async () => readResponseBody(response));",
    '    actualResponse = responseSnapshot({ response, responseBody, resolvedRequest, includeRequest: Boolean(testCase.debug || apiStep.debug) });',
    '',
    '    for (const assertion of apiStep.assertions) {',
    '      await test.step(assertionTitle(assertion), async () => {',
    '        await runAssertion({ assertion, response, responseBody, actualResponse, evidence });',
    '      });',
    '    }',
    '',
    '    for (const capture of apiStep.captures || []) {',
    '      await test.step(captureTitle(capture), async () => {',
    '        runCapture({ capture, response, responseBody, variables, evidence, includeSecrets: Boolean(testCase.debug || apiStep.debug) });',
    '      });',
    '    }',
    '  } catch (error) {',
    '    failure = error;',
    '    throw error;',
    '  } finally {',
    '    await writeApiEvidence({',
    '      testCase,',
    '      apiStep,',
    '      resolvedRequest,',
    '      response,',
    '      responseBody,',
    '      actualResponse,',
    '      evidence,',
    '      startedAt,',
    '      durationMs: Date.now() - startedMs,',
    '      failure,',
    '      includeSecrets: Boolean(testCase.debug || apiStep.debug)',
    '    });',
    '  }',
    '}',
    '',
    'function requestOptions(apiRequest) {',
    '  const options = { method: apiRequest.method };',
    '  if (apiRequest.headers && Object.keys(apiRequest.headers).length) options.headers = apiRequest.headers;',
    '  if (apiRequest.query && Object.keys(apiRequest.query).length) options.params = apiRequest.query;',
    '  if (apiRequest.body !== undefined && apiRequest.body !== null) options.data = apiRequest.body;',
    '  return options;',
    '}',
    '',
    'function resolveRequestValue(value, variables = {}) {',
    '  if (Array.isArray(value)) return value.map((entry) => resolveRequestValue(entry, variables));',
    '  if (value && typeof value === "object") {',
    '    return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, resolveRequestValue(entry, variables)]));',
    '  }',
    '  if (typeof value !== "string") return value;',
    '  const exact = value.match(/^\\{\\{\\s*([A-Za-z_][A-Za-z0-9_]*)\\s*\\}\\}$/);',
    '  if (exact) return resolveVariable(exact[1], variables);',
    '  return value.replace(/\\{\\{\\s*([A-Za-z_][A-Za-z0-9_]*)\\s*\\}\\}/g, (_match, name) => String(resolveVariable(name, variables)));',
    '}',
    '',
    'function resolveVariable(name, variables) {',
    '  if (Object.prototype.hasOwnProperty.call(variables, name)) return variables[name];',
    '    const normalized = String(name).toUpperCase();',
    '  if (normalized === "EMAIL" || normalized === "PROGUIDE_USER_EMAIL") return requiredEnv("PROGUIDE_USER_EMAIL");',
    '  if (normalized === "USERNAME" || normalized === "PROGUIDE_USER_USERNAME") return requiredEnv("PROGUIDE_USER_USERNAME");',
    '  if (normalized === "PASSWORD" || normalized === "PROGUIDE_USER_PASSWORD") return requiredEnv("PROGUIDE_USER_PASSWORD");',
    '  throw new Error(`Missing API variable: ${name}`);',
    '}',
    '',
    'function requiredEnv(name) {',
    '  const value = process.env[name];',
    '  if (value === undefined || value === "") throw new Error(`Missing API credential env var: ${name}`);',
    '  return value;',
    '}',
    '',
    'async function readResponseBody(response) {',
    '  const text = await response.text();',
    "  if (!text) return null;",
    "  const contentType = response.headers()['content-type'] || '';",
    "  if (contentType.includes('json') || /^[\\s]*[\\[{]/.test(text)) {",
    '    try {',
    '      return JSON.parse(text);',
    '    } catch {',
    '      return text;',
    '    }',
    '  }',
    '  return text;',
    '}',
    '',
    'async function applyAssertion({ assertion, response, responseBody, actualResponse }) {',
    '  try {',
    '    await applyAssertionCore({ assertion, response, responseBody });',
    '  } catch (error) {',
    '    throw enrichAssertionError(error, assertion, actualResponse);',
    '  }',
    '}',
    '',
    'async function runAssertion({ assertion, response, responseBody, actualResponse, evidence }) {',
    '  try {',
    '    await applyAssertion({ assertion, response, responseBody, actualResponse });',
    "    evidence.assertions.push({ assertion, status: 'passed' });",
    '  } catch (error) {',
    "    evidence.assertions.push({ assertion, status: 'failed', message: shortErrorMessage(error) });",
    '    throw error;',
    '  }',
    '}',
    '',
    'async function applyAssertionCore({ assertion, response, responseBody }) {',
    "  if (assertion.type === 'status') {",
    '    expect(response.status()).toBe(assertion.expected);',
    '    return;',
    '  }',
    "  if (assertion.type === 'ok') {",
    '    expect(response.ok()).toBeTruthy();',
    '    return;',
    '  }',
    "  if (assertion.type === 'header') {",
    "    const actual = response.headers()[String(assertion.name || '').toLowerCase()] || '';",
    "    if (assertion.operator === 'contains') expect(actual).toContain(String(assertion.expected));",
    '    else expect(actual).toBe(String(assertion.expected));',
    '    return;',
    '  }',
    "  if (assertion.type === 'body_contains') {",
    "    const text = typeof responseBody === 'string' ? responseBody : JSON.stringify(responseBody);",
    '    expect(text).toContain(String(assertion.expected));',
    '    return;',
    '  }',
    "  if (assertion.type === 'body_path') {",
    '    const actual = valueAtPath(responseBody, assertion.path);',
    "    if (assertion.operator === 'exists') {",
    '      expect(actual).not.toBeUndefined();',
    '      return;',
    '    }',
    "    if (assertion.operator === 'is_array') {",
    '      expect(Array.isArray(actual)).toBeTruthy();',
    '      return;',
    '    }',
    "    if (assertion.operator === 'contains') {",
    '      if (Array.isArray(actual)) expect(actual).toContain(assertion.expected);',
    '      else expect(String(actual)).toContain(String(assertion.expected));',
    '      return;',
    '    }',
    '    expect(actual).toEqual(assertion.expected);',
    '    return;',
    '  }',
    "  throw new Error(`Unsupported API assertion: ${JSON.stringify(assertion)}`);",
    '}',
    '',
    'function enrichAssertionError(error, assertion, actualResponse) {',
    '  const payload = { assertion, actual_response: actualResponse };',
    '  const pretty = JSON.stringify(payload, null, 2);',
    '  const compact = JSON.stringify(payload);',
    "  const encoded = Buffer.from(compact, 'utf8').toString('base64');",
    '  const baseMessage = error?.message || String(error);',
    '  const message = `${baseMessage}\\n\\nProGuide API debug:\\n${pretty}\\nPROGUIDE_API_DEBUG_BASE64 ${encoded}`;',
    '  const enriched = new Error(message);',
    '  enriched.stack = error?.stack ? `${message}\\n${error.stack}` : message;',
    '  return enriched;',
    '}',
    '',
    'function responseSnapshot({ response, responseBody, resolvedRequest, includeRequest }) {',
    '  const snapshot = {',
    '    status: response.status(),',
    '    ok: response.ok(),',
    '    headers: response.headers(),',
    '    body: truncateForDebug(responseBody)',
    '  };',
    '  if (includeRequest) snapshot.request = truncateForDebug({',
    '    method: resolvedRequest.method,',
    '    path: resolvedRequest.path,',
    '    headers: resolvedRequest.headers || {},',
    '    query: resolvedRequest.query || {},',
    '    body: resolvedRequest.body',
    '  });',
    '  return snapshot;',
    '}',
    '',
    'function truncateForDebug(value) {',
    '  const limit = 12000;',
    '  if (typeof value === "string") return value.length > limit ? `${value.slice(0, limit)}...<truncated>` : value;',
    '  if (value === null || value === undefined) return value;',
    '  const text = JSON.stringify(value);',
    '  if (!text || text.length <= limit) return value;',
    '  return `${text.slice(0, limit)}...<truncated>`;',
    '}',
    '',
    'function applyCapture({ capture, response, responseBody, variables }) {',
    '  let value;',
    "  if (capture.source === 'header') {",
    "    value = response.headers()[String(capture.header || '').toLowerCase()];",
    '  } else {',
    '    value = valueAtPath(responseBody, capture.path);',
    '  }',
    '  if (value === undefined) throw new Error(`Capture ${capture.name} did not resolve`);',
    '  variables[capture.name] = value;',
    '  return value;',
    '}',
    '',
    'function runCapture({ capture, response, responseBody, variables, evidence, includeSecrets }) {',
    '  try {',
    '    const value = applyCapture({ capture, response, responseBody, variables });',
    '    evidence.captures.push({',
    "      name: capture.name,",
    "      source: capture.source || 'body',",
    '      path: capture.path || null,',
    '      header: capture.header || null,',
    "      status: 'captured',",
    '      value: sanitizeForEvidence(value, { includeSecrets, key: capture.name })',
    '    });',
    '  } catch (error) {',
    '    evidence.captures.push({',
    "      name: capture.name,",
    "      source: capture.source || 'body',",
    '      path: capture.path || null,',
    '      header: capture.header || null,',
    "      status: 'failed',",
    '      message: shortErrorMessage(error)',
    '    });',
    '    throw error;',
    '  }',
    '}',
    '',
    'function valueAtPath(source, path) {',
    '  if (source === null || source === undefined) return undefined;',
    "  const normalizedPath = String(path ?? '').trim();",
    "  if (!normalizedPath || normalizedPath === '$') return source;",
    "  const parts = normalizedPath.replace(/^\\$\\./, '').replace(/^\\$/, '').replace(/\\[(\\d+)\\]/g, '.$1').split('.').filter(Boolean);",
    '  let current = source;',
    '  for (const part of parts) {',
    '    if (current === null || current === undefined) return undefined;',
    '    current = current[part];',
    '  }',
    '  return current;',
    '}',
    '',
    'function assertionTitle(assertion) {',
    "  if (assertion.type === 'status') return `status is ${assertion.expected}`;",
    "  if (assertion.type === 'ok') return 'response is successful';",
    "  if (assertion.type === 'header') return `header ${assertion.name} ${assertion.operator || 'equals'} ${assertion.expected}`;",
    "  if (assertion.type === 'body_contains') return `body contains ${assertion.expected}`;",
    "  if (assertion.type === 'body_path') return `body.${assertion.path || '<root>'} ${assertion.operator || 'equals'} ${assertion.expected ?? ''}`;",
    "  if (assertion.type === 'unsupported') return `unsupported assertion ${assertion.reason || ''}`;",
    "  return 'api assertion';",
    '}',
    '',
    'function captureTitle(capture) {',
    "  if (capture.source === 'header') return `capture ${capture.name} from header ${capture.header}`;",
    "  return `capture ${capture.name} from body.${capture.path || '<root>'}`;",
    '}',
    '',
    'async function writeApiEvidence({ testCase, apiStep, resolvedRequest, response, responseBody, actualResponse, evidence, startedAt, durationMs, failure, includeSecrets }) {',
    '  const runDir = process.env.PROGUIDE_RUN_DIR;',
    '  if (!runDir) return;',
    '  const payload = {',
    '    kind: "api_evidence",',
    '    case_id: testCase.id,',
    '    case_title: testCase.title,',
    '    step_id: apiStep.id || `request_${apiStep.sequence || 1}`,',
    '    step_title: apiStep.title || `${apiStep.request.method} ${apiStep.request.path}`,',
    '    sequence: apiStep.sequence || 1,',
    '    started_at: startedAt,',
    '    finished_at: new Date().toISOString(),',
    '    duration_ms: durationMs,',
    '    redacted: !includeSecrets,',
    '    request: evidenceRequestSnapshot(resolvedRequest, includeSecrets),',
    '    response: response ? evidenceResponseSnapshot({ response, responseBody, includeSecrets }) : null,',
    '    assertions: evidence.assertions || [],',
    '    captures: evidence.captures || [],',
    '    error: failure ? shortErrorMessage(failure) : null',
    '  };',
    '  try {',
    '    const directory = path.join(runDir, "api_evidence", safeEvidenceName(testCase.id));',
    '    await fs.mkdir(directory, { recursive: true });',
    '    const fileName = `${String(payload.sequence).padStart(2, "0")}_${safeEvidenceName(payload.step_id)}.json`;',
    '    await fs.writeFile(path.join(directory, fileName), JSON.stringify(payload, null, 2), "utf8");',
    '  } catch (error) {',
    '    console.warn(`ProGuide could not write API evidence: ${error?.message || error}`);',
    '  }',
    '}',
    '',
    'function evidenceRequestSnapshot(request, includeSecrets) {',
    '  return {',
    '    method: request.method,',
    '    path: request.path,',
    '    url: absoluteUrl(request.path),',
    '    headers: sanitizeForEvidence(request.headers || {}, { includeSecrets }),',
    '    query: sanitizeForEvidence(request.query || {}, { includeSecrets }),',
    '    body: sanitizeForEvidence(request.body, { includeSecrets })',
    '  };',
    '}',
    '',
    'function evidenceResponseSnapshot({ response, responseBody, includeSecrets }) {',
    '  return {',
    '    status: response.status(),',
    '    ok: response.ok(),',
    '    headers: sanitizeForEvidence(response.headers(), { includeSecrets }),',
    '    body: sanitizeForEvidence(truncateForDebug(responseBody), { includeSecrets })',
    '  };',
    '}',
    '',
    'function absoluteUrl(requestPath) {',
    '  const text = String(requestPath || "");',
    '  if (/^https?:\\/\\//i.test(text)) return text;',
    '  const base = String(process.env.PROGUIDE_BASE_URL || "").replace(/\\/+$/, "");',
    '  if (!base) return text;',
    '  return `${base}${text.startsWith("/") ? "" : "/"}${text}`;',
    '}',
    '',
    'function sanitizeForEvidence(value, options = {}) {',
    '  const includeSecrets = Boolean(options.includeSecrets);',
    '  const key = String(options.key || "");',
    '  if (!includeSecrets && isSensitiveKey(key)) return "[REDACTED]";',
    '  if (Array.isArray(value)) return value.map((entry) => sanitizeForEvidence(entry, options));',
    '  if (value && typeof value === "object") {',
    '    return Object.fromEntries(Object.entries(value).map(([entryKey, entryValue]) => [',
    '      entryKey,',
    '      sanitizeForEvidence(entryValue, { includeSecrets, key: entryKey })',
    '    ]));',
    '  }',
    '  return value;',
    '}',
    '',
    'function isSensitiveKey(key) {',
    '  return /authorization|cookie|password|pass|secret|token|api[_-]?key/i.test(String(key || ""));',
    '}',
    '',
    'function safeEvidenceName(value) {',
    '  return String(value || "item").replace(/[^A-Za-z0-9_.-]+/g, "_").slice(0, 120) || "item";',
    '}',
    '',
    'function shortErrorMessage(error) {',
    '  return String(error?.message || error || "").split("\\n\\nProGuide API debug:")[0].trim();',
    '}',
    ''
  ].join('\n');
}

function normalizeApiPlanRequests(testCase) {
  const flowRequests = normalizeApiRequests(testCase.requests || []);
  if (flowRequests.length) return flowRequests;
  const request = normalizeApiRequest({
    ...(testCase.request || {}),
    route: testCase.route,
    steps: testCase.steps || [],
    expected: testCase.expected || []
  });
  return [{
    id: 'request_1',
    title: `${request.method} ${request.path}`,
    request,
    assertions: normalizeApiAssertions({
      assertions: testCase.assertions || [],
      expected: testCase.expected || [],
      expectedStatus: request.expected_status
    }),
    captures: normalizeApiCaptures(testCase.captures ?? testCase.save ?? testCase.extract),
    debug: Boolean(testCase.debug)
  }];
}
